apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
  namespace: {{ .Values.namespace }}
data:
  DB_URL: "{{ .Values.DB_URL }}"
  DB_USER: "{{ .Values.DB_USER }}"
  DB_PASSWORD: "{{ .Values.DB_PASSWORD }}"