spring:
  #datasource:
  #  url: jdbc:h2:mem:mydb
  #  username: sa
  #  password: password
  #  driverClassName: org.h2.Driver
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver 
logging:
  level:
    ru.pilot: debug