version: '3.9'
name: user-full-app
services:
  postgres:
    container_name: postgres_container
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - "D:\\db\\postgres:/data/postgres"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-user-db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    restart: unless-stopped
    networks:
      - postgres
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:6.9
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - postgres
  
  user-app:
    container_name: user-app
    image: pilot_repo/user_app:1.0
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      POSTGRES_DB: jdbc:postgresql://postgres_container:5432/user-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
