version: '3.9'
name: my_postgres
services:
  postgres:
    container_name: my_postgres_container
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - "D:\\db\\postgres:/data/postgres"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-user-db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    restart: unless-stopped
    networks:
      - postgres
  
  pgadmin:
    container_name: my_pgadmin_container
    image: dpage/pgadmin4:6.9
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
