namespace: &namespace preprod
appHost: user-app
# postgres должен быть запущен в кубере, через helm -> .charts\postgres
DB_URL: jdbc:postgresql://postgres-service.preprod:80/postgres
DB_USER: postgres
DB_PASSWORD: postgres

apps:
  backend:
    namespace: *namespace
    replicasCount: 2
    container:
      env:
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: user-app-config
              key: DB_URL
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: user-app-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: user-app-config
              key: DB_PASSWORD